# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 8, 11, 17, 21, 25 ]
        include:
          - jdk: 8
            gradle: 6.9.4
          - jdk: 11
            gradle: 8.3
          - jdk: 17
            gradle: 9.1.0
          - jdk: 21
            gradle: 9.1.0
          - jdk: 25
            gradle: 9.1.0
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
          cache: maven  # uses actions/cache@v4 internally
      # 3. Install Gradle
      - name: Set up Gradle ${{ matrix.gradle }}
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: ${{ matrix.gradle }}
      # 4. Verify Gradle version
      - name: Check Gradle version
        run: gradle --version
      # 5. Install Maven 3.9.9 manually
      - name: Install Maven 3.9.9
        run: |
          curl -s https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz \
          | tar -xz -C /tmp
          sudo mv /tmp/apache-maven-3.9.9 /opt/maven
          echo "M2_HOME=/opt/maven" >> $GITHUB_ENV
          echo "/opt/maven/bin" >> $GITHUB_PATH
          mvn -version

      # 6. Install TeX dependencies
      - name: Install TeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-publishers biber

      # 7. Build with Maven
      - name: Build with Maven
        run: mvn -B install --file pom.xml
